version: "3"

services:
  
  airthings-mqtt-ha:
    build:
      context: ./
    
    container_name: airthings-mqtt-ha
    image: mjmccans/airthings-mqtt-ha:latest
          
    tty: true
    stdin_open: true

    restart: unless-stopped

    volumes:
      - ./src/options.json:/code/options.json # Location of options.json file
      - /var/run/dbus:/var/run/dbus:z         # Connect to the host dbus
